name: 'Generate component labels'
on:
  push:
    branches: [main]
    paths:
      - .github/CODEOWNERS
      - ./.github/workflows/generate-component-labels.yml
      - ./.github/workflows/scripts/generate-component-labels.sh
    workflow_dispatch:

jobs:
  generate-component-labels:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'open-telemetry' }}
    steps:
      - uses: actions/checkout@v3

      - name: Generate component labels
        run: ./.github/workflows/scripts/generate-component-labels.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

