ignore:
  - "dataset-go"
  - "opentelemetry-collector-contrib"
  - "otelcol-dataset"

codecov:
  # Avoid "Missing base report" issues
  allow_coverage_offsets: true
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2         # decimal places to display: 0 <= value <= 4
  round: nearest
  range: 50...90      # custom range of coverage colors from red -> yellow -> green

  status:
    project:
      default:
        target: auto
        threshold: 2%
        base: auto
    patch:
      default:
        target: auto
        threshold: 5%
        base: auto

github_checks:
    annotations: false

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: yes
  require_head: yes

fixes:
  - "github.com/open-telemetry/opentelemetry-collector-contrib/::scalyr-opentelemetry-collector-contrib/"
