blank_issues_enabled: false
contact_links:
  - name: OpenTelemetry Collector Slack Channel
    url: https://cloud-native.slack.com/archives/C01N6P7KR6W
    about: Please ask and answer questions here.
