name: "Project: Tidy"
on:
  pull_request_target:
    types: [opened, ready_for_review, synchronize, reopened, labeled, unlabeled]
    branches:
      - main

env:
  # Make sure to exit early if cache segment download times out after 2 minutes.
  # We limit cache download as a whole to 5 minutes.
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2

jobs:
  setup-environment:
    # disabling until permission issues is resolved
    # see: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/22953
    if: ${{ false }}
    timeout-minutes: 30
    runs-on: ubuntu-latest
    # if: ${{ contains(github.event.pull_request.labels.*.name, 'dependencies') }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "renovate-bot/open-telemetry-_-opentelemetry-collector-contrib"
          ref: ${{ github.head_ref }}
          token: ${{ secrets.OPENTELEMETRYBOT_GITHUB_TOKEN }}
      - uses: actions/setup-go@v4
        with:
          go-version: ~1.20.7
          cache: false
      - name: Cache Go
        id: go-cache
        timeout-minutes: 5
        uses: actions/cache@v3
        with:
          path: |
            ~/go/bin
            ~/go/pkg/mod
          key: go-cache-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
      - name: Install dependencies
        if: steps.go-cache.outputs.cache-hit != 'true'
        run: make -j2 gomoddownload
      - name: Install Tools
        if: steps.go-cache.outputs.cache-hit != 'true'
        run: make install-tools
      - name: go mod tidy
        run: |
          make gotidy
          git config user.name opentelemetrybot
          git config user.email 107717825+opentelemetrybot@users.noreply.github.com
          echo "git diff --exit-code || (git add . && git commit -m \"go mod tidy\" && git push)"
          git diff --exit-code || (git add . && git commit -m "go mod tidy" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.OPENTELEMETRYBOT_GITHUB_TOKEN }}
