# Copyright The OpenTelemetry Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3.9'
x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"

networks:
  default:
    name: otel-rel
    driver: bridge

services:
  # OpenTelemetry Collector
  dataset-collector-rel:
    image: otelcol-dataset
    container_name: dataset-collector-rel
    deploy:
      resources:
        limits:
          memory: 2G
    restart: unless-stopped
    command: [ "--config=/tmp/otel-config.yaml" ]
    volumes:
      # stores otel config and test results
      - ./:/tmp/
      # - /var/lib/docker/containers:/var/lib/docker/containers
    ports:
      - "4318:4318"     # OTLP over HTTP receiver
    logging: *logging
    depends_on:
      - dataset-dummy-server-rel

  # Dummy Server
  # TODO(Tomaz): Which should build the image here (if doesn't exist) to make this file more
  # standalone and not depending on external make targets, etc.
  dataset-dummy-server-rel:
    image: dataset-dummy-server
    container_name: dataset-dummy-server-rel
    deploy:
      resources:
        limits:
          memory: 500M
    restart: unless-stopped
    ports:
      - "8000:8000"
    logging: *logging

  server-control-rel:
    image: curlimages/curl
    container_name: server-control-rel
    deploy:
      resources:
        limits:
          memory: 500M
    restart: unless-stopped
    depends_on:
      - dataset-dummy-server-rel
    volumes:
      - ./:/tmp/
    entrypoint: ["/tmp/server-control.sh", "100", "50"]
