# Use this changelog template to create an entry for release notes.

# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
change_type: enhancement

# The name of the component, or a single word describing the area of concern, (e.g. filelogreceiver)
component: opampsupervisor

# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
note: Add config validation for the supervisor config

# Mandatory: One or more tracking issues related to the change. You can use the PR number here if no issue exists.
issues: [32843]
